# -*- mode: python ; coding: utf-8 -*-
"""
SoundBot Backend PyInstaller Spec
打包为目录模式，支持 Windows/macOS/Linux
"""

import sys
import os
from pathlib import Path

# 获取当前 spec 文件所在目录
spec_file = Path(os.path.abspath(sys.argv[0]))
spec_dir = spec_file.parent
backend_dir = spec_dir
project_root = backend_dir.parent

block_cipher = None

# 数据文件配置 - 只包含代码，不包含模型
datas = []

# 添加 core 目录
if (backend_dir / 'core').exists():
    datas.append((str(backend_dir / 'core'), 'core'))

# 添加 utils 目录
if (backend_dir / 'utils').exists():
    datas.append((str(backend_dir / 'utils'), 'utils'))

# 添加 config.py
if (backend_dir / 'config.py').exists():
    datas.append((str(backend_dir / 'config.py'), '.'))

# 添加 models/schemas.py (Pydantic模型)
if (backend_dir / 'models').exists():
    datas.append((str(backend_dir / 'models'), 'models'))

# 添加 bootstrap.py
if (backend_dir / 'bootstrap.py').exists():
    datas.append((str(backend_dir / 'bootstrap.py'), '.'))

# 隐藏导入 - 包含所有需要的依赖
hiddenimports = [
    # FastAPI / Uvicorn
    'uvicorn',
    'uvicorn.logging',
    'uvicorn.loops',
    'uvicorn.loops.auto',
    'uvicorn.protocols',
    'uvicorn.protocols.http',
    'uvicorn.protocols.http.auto',
    'uvicorn.protocols.http.h11_impl',
    'uvicorn.protocols.websockets',
    'uvicorn.protocols.websockets.auto',
    'uvicorn.protocols.websockets.wsproto_impl',
    'uvicorn.protocols.websockets.websockets_impl',
    'fastapi',
    'fastapi.middleware.cors',
    'fastapi.middleware.trustedhost',
    'fastapi.middleware.httpsredirect',
    'fastapi.middleware.gzip',
    'fastapi.openapi',
    'fastapi.openapi.docs',
    'fastapi.openapi.utils',
    'starlette',
    'starlette.middleware',
    'starlette.middleware.cors',
    'starlette.middleware.errors',
    'starlette.middleware.exceptions',
    'starlette.middleware.gzip',
    'starlette.middleware.trustedhost',
    'starlette.middleware.httpsredirect',
    'starlette.responses',
    'starlette.routing',
    'starlette.status',
    'starlette.requests',
    'starlette.websockets',
    'starlette.background',
    'starlette.concurrency',
    'starlette.datastructures',
    'starlette.types',
    'starlette.config',
    'starlette.exceptions',
    'starlette.staticfiles',
    'starlette.templating',

    # 后端核心模块
    'core.database',
    'core.audio_cache',
    'core.websocket_manager',
    'core.playback_manager',
    'core.scanner',
    'core.embedder',
    'core.indexer',
    'core.searcher',
    'core.search_engine',
    'core.llm_config_manager',
    'core.llm_client',
    'core.ai_chat_service',
    'core.model_preloader',
    'core.ucs_keywords',

    # 数据库
    'chromadb',
    'chromadb.config',
    'chromadb.api',
    'chromadb.api.segment',
    'chromadb.api.models',
    'chromadb.db',
    'chromadb.db.sqlite',
    'chromadb.db.duckdb',
    'chromadb.collection',
    'chromadb.errors',
    'chromadb.telemetry',
    'chromadb.utils',
    'aiosqlite',
    'sqlite3',
    'sqlite3.dbapi2',

    # 数据验证
    'pydantic',
    'pydantic_settings',
    'pydantic_core',
    'pydantic.deprecated',
    'pydantic.deprecated.decorator',
    'pydantic.json_schema',
    'pydantic.root_model',
    'pydantic.v1',
    'pydantic.v1.fields',
    'pydantic.v1.main',
    'pydantic.v1.types',
    'annotated_types',
    'typing_extensions',

    # AI/ML 核心 - torch
    'torch',
    'torch.testing',
    'torch.nn',
    'torch.nn.modules',
    'torch.nn.modules.activation',
    'torch.nn.modules.batchnorm',
    'torch.nn.modules.container',
    'torch.nn.modules.conv',
    'torch.nn.modules.dropout',
    'torch.nn.modules.flatten',
    'torch.nn.modules.linear',
    'torch.nn.modules.loss',
    'torch.nn.modules.module',
    'torch.nn.modules.normalization',
    'torch.nn.modules.padding',
    'torch.nn.modules.pooling',
    'torch.nn.functional',
    'torch.nn.utils',
    'torch.nn.utils.rnn',
    'torch.utils',
    'torch.utils.data',
    'torch.utils.data.dataloader',
    'torch.utils.data.dataset',
    'torch.utils.data.sampler',
    'torch.cuda',
    'torch.backends',
    'torch.backends.cudnn',
    'torch.backends.mps',
    'torch.backends.cpu',
    'torch.optim',
    'torch.optim.adam',
    'torch.optim.adamw',
    'torch.optim.sgd',
    'torch.optim.lr_scheduler',
    'torch.distributed',
    'torch.multiprocessing',
    'torch.jit',
    'torch.jit._script',
    'torch.jit._trace',
    'torch.jit._onnx',
    'torch.jit._serialization',
    'torch._dynamo',
    'torch._dynamo.config',
    'torch._dynamo.backends',
    'torch._dynamo.utils',
    'torch._dynamo.output_graph',
    'torch._dynamo.bytecode_analysis',
    'torch._dynamo.bytecode_transformation',
    'torch._inductor',
    'torch._inductor.config',
    'torch._inductor.utils',
    'torch._inductor.codegen',
    'torch._inductor.graph',
    'torch._inductor.ir',
    'torch._C',
    'torch._VF',
    'torchaudio',
    'torchaudio.models',
    'torchaudio.utils',
    'torchvision',
    'torchvision.models',
    'torchvision.ops',
    'torchvision.transforms',

    # transformers
    'transformers',
    'transformers.utils',
    'transformers.utils.generic',
    'transformers.utils.import_utils',
    'transformers.configuration_utils',
    'transformers.feature_extraction_utils',
    'transformers.modeling_utils',
    'transformers.models',
    'transformers.models.clap',
    'transformers.models.clap.modeling_clap',
    'transformers.models.clap.configuration_clap',
    'transformers.models.clap.feature_extraction_clap',
    'transformers.models.clap.processing_clap',
    'transformers.models.clap.tokenization_clap',
    'transformers.models.clap.audio_processing_clap',
    'transformers.models.clap.modular_clap',
    'transformers.models.auto',
    'transformers.models.auto.modeling_auto',
    'transformers.models.auto.configuration_auto',
    'transformers.models.auto.tokenization_auto',
    'transformers.models.auto.feature_extraction_auto',
    'transformers.models.auto.processing_auto',
    'transformers.tokenization_utils',
    'transformers.tokenization_utils_base',
    'transformers.pipelines',
    'transformers.pipelines.base',
    'transformers.pipelines.audio_classification',
    'transformers.pipelines.automatic_speech_recognition',
    'sentence_transformers',
    'sentence_transformers.SentenceTransformer',
    'sentence_transformers.models',

    # 数值计算
    'numpy',
    'numpy.core',
    'numpy.core._dtype_ctypes',
    'numpy.core.multiarray',
    'numpy.core.numeric',
    'numpy.linalg',
    'numpy.linalg.linalg',
    'numpy.linalg._umath_linalg',
    'numpy.fft',
    'numpy.fft._pocketfft',
    'numpy.random',
    'numpy.random.mtrand',
    'numpy.lib',
    'numpy.lib.function_base',
    'scipy',
    'scipy.sparse',
    'scipy.sparse.csgraph',
    'scipy.sparse.linalg',
    'scipy.linalg',
    'scipy.linalg.cython_lapack',
    'scipy.linalg.flapack_gen',
    'scipy.special',
    'scipy.special._orthogonal',
    'scipy.integrate',
    'scipy.stats',
    'scipy.optimize',

    # 音频处理
    'librosa',
    'librosa.core',
    'librosa.core.audio',
    'librosa.core.spectrum',
    'librosa.feature',
    'librosa.feature.utils',
    'librosa.util',
    'librosa.display',
    'librosa.effects',
    'librosa.beat',
    'soundfile',
    'soundfile.library',
    'audioread',
    'audioread.rawread',
    'audioread.ffdec',
    'audioread.gdec',
    'mutagen',
    'mutagen.easymp4',
    'mutagen.mp4',
    'mutagen.flac',
    'mutagen.oggvorbis',
    'tinytag',
    'numba',
    'numba.core',
    'numba.core.runtime',
    'numba.core.compiler',
    'numba.core.cpu',
    'numba.misc',
    'llvmlite',
    'llvmlite.ir',
    'llvmlite.binding',
    'soxr',

    # 机器学习
    'sklearn',
    'sklearn.utils',
    'sklearn.utils._encode',
    'sklearn.utils._mask',
    'sklearn.preprocessing',
    'sklearn.preprocessing.data',
    'sklearn.preprocessing.label',
    'sklearn.decomposition',
    'sklearn.decomposition._dict_learning',
    'sklearn.decomposition._nmf',
    'sklearn.cluster',
    'sklearn.cluster._kmeans',
    'joblib',
    'joblib.externals',
    'joblib.externals.cloudpickle',
    'joblib.memory',
    'threadpoolctl',

    # 网络/HTTP
    'requests',
    'requests.api',
    'requests.models',
    'requests.sessions',
    'requests.adapters',
    'requests.cookies',
    'requests.exceptions',
    'requests.hooks',
    'requests.status_codes',
    'requests.structures',
    'requests.utils',
    'urllib3',
    'urllib3.util',
    'urllib3.request',
    'urllib3.response',
    'urllib3.connection',
    'urllib3.connectionpool',
    'urllib3.exceptions',
    'urllib3.fields',
    'urllib3.filepost',
    'urllib3.poolmanager',
    'httpx',
    'httpx._client',
    'httpx._config',
    'httpx._exceptions',
    'httpx._models',
    'httpx._types',
    'httpx._urls',
    'httpx._utils',
    'httpcore',
    'httpcore._sync',
    'httpcore._async',
    'httpcore._exceptions',
    'httpcore._models',
    'httpcore._backends',
    'h11',
    'h11._util',
    'h11._connection',
    'h11._events',
    'h11._headers',
    'h11._readers',
    'h11._state',
    'h11._writers',
    'h11._receivebuffer',

    # 工具库
    'jieba',
    'jieba.posseg',
    'jieba.analyse',
    'yaml',
    'yaml.cyaml',
    'yaml.constructor',
    'yaml.composer',
    'yaml.parser',
    'yaml.scanner',
    'yaml.reader',
    'yaml.resolver',
    'yaml.dumper',
    'yaml.loader',
    'yaml.representer',
    'yaml.serializer',
    'yaml.emitter',
    'regex',
    'regex._regex',
    'tokenizers',
    'tokenizers.implementations',
    'tokenizers.models',
    'tokenizers.trainers',
    'tokenizers.pre_tokenizers',
    'tokenizers.decoders',
    'tokenizers.processors',
    'tokenizers.normalizers',
    'safetensors',
    'safetensors.torch',
    'safetensors.numpy',
    'packaging',
    'packaging.version',
    'packaging.specifiers',
    'packaging.requirements',
    'filelock',
    'fsspec',
    'fsspec.implementations',
    'fsspec.utils',
    'tqdm',
    'tqdm.std',
    'tqdm.auto',
    'tqdm.utils',
    'tqdm.cli',

    # Hugging Face
    'huggingface_hub',
    'huggingface_hub.file_download',
    'huggingface_hub.utils',
    'huggingface_hub.constants',
    'huggingface_hub.hf_api',
    'huggingface_hub.repository',
    'huggingface_hub.snapshot_download',

    # ONNX Runtime
    'onnxruntime',
    'onnxruntime.capi',
    'onnxruntime.capi.onnxruntime_pybind11_state',

    # 其他
    'asyncio',
    'asyncio.base_events',
    'asyncio.coroutines',
    'asyncio.events',
    'asyncio.queues',
    'asyncio.tasks',
    'asyncio.streams',
    'asyncio.subprocess',
    'asyncio.threads',
    'concurrent.futures',
    'concurrent.futures._base',
    'concurrent.futures.process',
    'concurrent.futures.thread',
    'pathlib',
    'pathlib._local',
    'json',
    'json.decoder',
    'json.encoder',
    're',
    'math',
    'random',
    'datetime',
    'hashlib',
    'hashlib._md5',
    'hashlib._sha1',
    'hashlib._sha256',
    'hashlib._sha512',
    'urllib',
    'urllib.parse',
    'urllib.request',
    'collections',
    'collections.abc',
    'functools',
    'functools._functools',
    'itertools',
    'itertools._itertools',
    'contextlib',
    'contextlib._contextlib',
    'typing',
    'typing.io',
    'typing.re',
    'inspect',
    'warnings',
    'warnings._warnings',
    'traceback',
    'traceback.format_exc',
    'logging',
    'logging.handlers',
    'logging.config',
    'io',
    'io.BytesIO',
    'io.StringIO',
    'struct',
    'weakref',
    'gc',
    'sys',
    'os',
    'time',
    'shutil',
    'tempfile',
    'errno',
    'signal',
    'mmap',
    'zipfile',
    'zipfile._path',
    'tarfile',
    'gzip',
    'bz2',
    'lzma',
    'copy',
    'pickle',
    'pickle._pickle',
    'base64',
    'binascii',
    'calendar',
    'codecs',
    'copyreg',
    'dis',
    'getopt',
    'getpass',
    'glob',
    'linecache',
    'optparse',
    'pprint',
    'queue',
    'quopri',
    'reprlib',
    'shlex',
    'string',
    'textwrap',
    'token',
    'tokenize',
    'types',
    'typing_extensions._utils',
    'urllib.error',
    'urllib.robotparser',
    'uuid',
    'decimal',
    'fractions',
    'numbers',
    'statistics',
    'bisect',
    'heapq',
    'array',
    'enum',
    'dataclasses',
    'abc',
    'atexit',
    'builtins',
]

# 分析阶段 - 完整构建，不排除任何依赖
a = Analysis(
    [str(backend_dir / 'main.py')],
    pathex=[str(backend_dir)],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
    optimize=1,
)

# 过滤掉不需要的二进制文件
binaries_to_exclude = [
    'Qt5', 'Qt6', 'QtCore', 'QtGui', 'QtWidgets',
    'opencv', 'cv2',
    'tk', 'tcl',
]
a.binaries = [b for b in a.binaries if not any(x in str(b[0]) for x in binaries_to_exclude)]

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

# onedir 模式
exe_name = 'soundbot-backend'
exe_name_with_ext = exe_name + ('.exe' if sys.platform == 'win32' else '')

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name=exe_name_with_ext,
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    runtime_tmpdir=None,
    console=True,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name=exe_name,
    strip=False,
    upx=False,
    runtime_tmpdir=None,
)
